# Generated by Django 2.0.6 on 2021-04-22 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='機種名')),
                ('number', models.IntegerField(verbose_name='台番号')),
                ('date', models.DateField(default=datetime.datetime(2021, 4, 22, 14, 45, 33, 846081), verbose_name='日付')),
                ('bigbonus', models.IntegerField(verbose_name='BB')),
                ('regularbonus', models.IntegerField(verbose_name='RB')),
                ('count', models.IntegerField(verbose_name='総回転数')),
                ('payout', models.IntegerField(verbose_name='差枚数')),
                ('memo', models.CharField(max_length=50, verbose_name='メモ')),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
