# Generated by Django 2.0.6 on 2021-04-22 06:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2021, 4, 22, 15, 36, 0, 996028), verbose_name='日付')),
            ],
            options={
                'verbose_name': '日付',
                'verbose_name_plural': '日付',
                'db_table': 'date',
            },
        ),
        migrations.CreateModel(
            name='StoreName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '店舗一覧',
                'verbose_name_plural': '店舗一覧',
                'db_table': 'store_name',
            },
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'コンサートホール', 'verbose_name_plural': 'コンサートホール'},
        ),
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pss.Date', verbose_name='日付'),
        ),
        migrations.AlterModelTable(
            name='data',
            table='data',
        ),
        migrations.AddField(
            model_name='date',
            name='store_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pss.StoreName', verbose_name='店舗名'),
        ),
    ]
