# Generated by Django 2.0.6 on 2021-04-22 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pss', '0002_auto_20210422_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 22, 15, 44, 16, 345187), verbose_name='日付'),
        ),
    ]
