# Generated by Django 2.0.6 on 2021-04-22 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pss', '0004_auto_20210422_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='store_name',
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'データ一覧', 'verbose_name_plural': 'データ一覧'},
        ),
        migrations.AddField(
            model_name='data',
            name='store_name',
            field=models.CharField(default='コンサートホール', max_length=100, verbose_name='店舗名'),
        ),
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 22, 15, 58, 50, 677210), verbose_name='日付'),
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.DeleteModel(
            name='StoreName',
        ),
    ]
