# Generated by Django 2.0.6 on 2021-04-26 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pss', '0007_auto_20210422_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pay', models.IntegerField(verbose_name='総差枚数')),
                ('date', models.DateField(default=datetime.datetime(2021, 4, 26, 15, 16, 53, 145664), verbose_name='日付')),
            ],
            options={
                'verbose_name': '差枚数',
                'verbose_name_plural': '差枚数',
                'db_table': 'pay',
            },
        ),
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 26, 15, 16, 53, 145095), verbose_name='日付'),
        ),
    ]
