# Generated by Django 2.0.6 on 2021-04-26 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pss', '0009_auto_20210426_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 26, 15, 20, 59, 160227), verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='totalpay',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 26, 15, 20, 59, 160876), verbose_name='日付'),
        ),
    ]
